In [66]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [67]:

data={'name':['Sumit','Rahul','Ankit'],
      'age':[25,30,35],
      'salary':[25000,30000,35000]
      }

df=pd.DataFrame(data)
df

    name  age  salary
0  Sumit   25   25000
1  Rahul   30   30000
2  Ankit   35   35000

In [68]:
df=pd.read_csv('D:\Revision-Pandas_SQL\data\orders.csv')
df.head()

<>:1: SyntaxWarning: invalid escape sequence '\R'
<>:1: SyntaxWarning: invalid escape sequence '\R'
C:\Users\Mukesh\AppData\Local\Temp\ipykernel_33860\2827182933.py:1: SyntaxWarning: invalid escape sequence '\R'
  df=pd.read_csv('D:\Revision-Pandas_SQL\data\orders.csv')

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5

In [69]:
df.tail()

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [70]:
df.head(10)

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5

In [71]:
df.tail(10)

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [72]:
df.columns

Index(['order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_id',
       'region', 'product_id', 'category', 'sales', 'quantity', 'profit'],
      dtype='object')

In [73]:
df.dtypes

order_id        object
order_date      object
ship_date       object
ship_mode       object
customer_id     object
region          object
product_id      object
category        object
sales          float64
quantity         int64
profit         float64
dtype: object

In [74]:
df.shape

(50, 11)

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     50 non-null     object
 1   order_date   50 non-null     object
 2   ship_date    50 non-null     object
 3   ship_mode    50 non-null     object
 4   customer_id  50 non-null     object
 5   region       50 non-null     object
 6   product_id   50 non-null     object
 7   category     50 non-null     object
 8   sales        50 non-null     float64
 9   quantity     50 non-null     int64
 10  profit       50 non-null     float64
dtypes: float64(2), int64(1), object(8)
memory usage: 4.4+ KB

In [76]:
df.describe() #to show statistical summary

             sales   quantity       profit
count    50.000000  50.000000    50.000000
mean    300.792000   3.920000   -20.550000
std     547.564035   1.977836   251.767027
min       2.500000   2.000000 -1665.100000
25%      20.075000   2.000000     2.500000
50%      74.650000   3.000000     8.350000
75%     249.875000   5.000000    17.650000
max    3083.400000   9.000000   240.300000

In [77]:
df.columns

Index(['order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_id',
       'region', 'product_id', 'category', 'sales', 'quantity', 'profit'],
      dtype='object')

In [78]:
#to rename columns
df.rename(columns={'customer_id':'customer_key'},inplace=True)
df.columns

Index(['order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_key',
       'region', 'product_id', 'category', 'sales', 'quantity', 'profit'],
      dtype='object')

In [79]:
#to rename columns
df.rename(columns={'customer_key':'customer_id'},inplace=True)
df.columns

Index(['order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_id',
       'region', 'product_id', 'category', 'sales', 'quantity', 'profit'],
      dtype='object')

# Selection of columns

In [80]:
# col=['order_id','order_date','ship_date']
# df[col]
df_new=df[['order_id','order_date','ship_date']]
df_new.head()

         order_id  order_date   ship_date
0  CA-2020-152156  08-11-2020  11-11-2020
1  CA-2020-152156  08-11-2020  11-11-2020
2  CA-2020-138688  12-06-2020  16-06-2020
3  US-2019-108966  11-10-2019  18-10-2019
4  US-2019-108966  11-10-2019  18-10-2019

In [81]:
df['order_id']

0     CA-2020-152156
1     CA-2020-152156
2     CA-2020-138688
3     US-2019-108966
4     US-2019-108966
5     CA-2018-115812
6     CA-2018-115812
7     CA-2018-115812
8     CA-2018-115812
9     CA-2018-115812
10    CA-2018-115812
11    CA-2018-115812
12    CA-2021-114412
13    CA-2020-161389
14    US-2019-118983
15    US-2019-118983
16    CA-2018-105893
17    CA-2018-167164
18    CA-2018-143336
19    CA-2018-143336
20    CA-2018-143336
21    CA-2020-137330
22    CA-2020-137330
23    US-2021-156909
24    CA-2019-106320
25    CA-2020-121755
26    CA-2020-121755
27    US-2019-150630
28    US-2019-150630
29    US-2019-150630
30    US-2019-150630
31    US-2019-150630
32    US-2019-150630
33    US-2019-150630
34    CA-2021-107727
35    CA-2020-117590
36    CA-2020-117590
37    CA-2019-117415
38    CA-2019-117415
39    CA-2019-117415
40    CA-2019-117415
41    CA-2021-120999
42    CA-2020-101343
43    CA-2021-139619
44    CA-2020-118255
45    CA-2020-118255
46    CA-2018-146703
47    CA-2020-169194
48    CA-2020-169194
49    CA-2019-115742
Name: order_id, dtype: object

In [82]:
df.order_id

0     CA-2020-152156
1     CA-2020-152156
2     CA-2020-138688
3     US-2019-108966
4     US-2019-108966
5     CA-2018-115812
6     CA-2018-115812
7     CA-2018-115812
8     CA-2018-115812
9     CA-2018-115812
10    CA-2018-115812
11    CA-2018-115812
12    CA-2021-114412
13    CA-2020-161389
14    US-2019-118983
15    US-2019-118983
16    CA-2018-105893
17    CA-2018-167164
18    CA-2018-143336
19    CA-2018-143336
20    CA-2018-143336
21    CA-2020-137330
22    CA-2020-137330
23    US-2021-156909
24    CA-2019-106320
25    CA-2020-121755
26    CA-2020-121755
27    US-2019-150630
28    US-2019-150630
29    US-2019-150630
30    US-2019-150630
31    US-2019-150630
32    US-2019-150630
33    US-2019-150630
34    CA-2021-107727
35    CA-2020-117590
36    CA-2020-117590
37    CA-2019-117415
38    CA-2019-117415
39    CA-2019-117415
40    CA-2019-117415
41    CA-2021-120999
42    CA-2020-101343
43    CA-2021-139619
44    CA-2020-118255
45    CA-2020-118255
46    CA-2018-146703
47    CA-2020-169194
48    CA-2020-169194
49    CA-2019-115742
Name: order_id, dtype: object

In [83]:
type(df)

pandas.core.frame.DataFrame

# Series: DataFrame with single column

In [84]:
df_new_1=df['order_id']

In [85]:
df_new_1

0     CA-2020-152156
1     CA-2020-152156
2     CA-2020-138688
3     US-2019-108966
4     US-2019-108966
5     CA-2018-115812
6     CA-2018-115812
7     CA-2018-115812
8     CA-2018-115812
9     CA-2018-115812
10    CA-2018-115812
11    CA-2018-115812
12    CA-2021-114412
13    CA-2020-161389
14    US-2019-118983
15    US-2019-118983
16    CA-2018-105893
17    CA-2018-167164
18    CA-2018-143336
19    CA-2018-143336
20    CA-2018-143336
21    CA-2020-137330
22    CA-2020-137330
23    US-2021-156909
24    CA-2019-106320
25    CA-2020-121755
26    CA-2020-121755
27    US-2019-150630
28    US-2019-150630
29    US-2019-150630
30    US-2019-150630
31    US-2019-150630
32    US-2019-150630
33    US-2019-150630
34    CA-2021-107727
35    CA-2020-117590
36    CA-2020-117590
37    CA-2019-117415
38    CA-2019-117415
39    CA-2019-117415
40    CA-2019-117415
41    CA-2021-120999
42    CA-2020-101343
43    CA-2021-139619
44    CA-2020-118255
45    CA-2020-118255
46    CA-2018-146703
47    CA-2020-169194
48    CA-2020-169194
49    CA-2019-115742
Name: order_id, dtype: object

In [86]:
type(df_new_1)

pandas.core.series.Series

# Selectign rows,columns :loc,iloc

## iloc:index location - > fetches rowa and columns purely based on indexes

In [87]:
#select rows and columns based on index
df.iloc[0:5] #iloc=index location

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5

In [88]:
df.iloc[3:5]

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5

In [89]:
df.iloc[3:]

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [90]:
df.iloc[:4]

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0

In [91]:
df.iloc[::-1]

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9

In [92]:
#to fetch only a particular rows.. pass the list of the indexes
df.iloc[[3,5,18]]

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5

In [93]:
#we can also specify which columns we want
df.iloc[[2,5,8],0:4]

         order_id  order_date   ship_date       ship_mode
2  CA-2020-138688  12-06-2020  16-06-2020    Second Class
5  CA-2018-115812  09-06-2018  14-06-2018  Standard Class
8  CA-2018-115812  09-06-2018  14-06-2018  Standard Class

In [94]:
df.iloc[[2,5,8],[5,6]]

  region       product_id
2   West  OFF-LA-10000240
5   West  FUR-FU-10001487
8   West  OFF-BI-10003910

## loc : fetches rows based on index values(not index location like iloc),and we can mention columns names too(in iloc we were only able to give index locations)

In [95]:
df_new_2=df.loc[0:10,['order_id','order_date','sales']]
df_new_2

          order_id  order_date   sales
0   CA-2020-152156  08-11-2020   262.0
1   CA-2020-152156  08-11-2020   731.9
2   CA-2020-138688  12-06-2020    14.6
3   US-2019-108966  11-10-2019   957.6
4   US-2019-108966  11-10-2019    22.4
5   CA-2018-115812  09-06-2018    48.9
6   CA-2018-115812  09-06-2018     7.3
7   CA-2018-115812  09-06-2018   907.2
8   CA-2018-115812  09-06-2018    18.5
9   CA-2018-115812  09-06-2018   114.9
10  CA-2018-115812  09-06-2018  1706.2

In [96]:
df.set_index('order_id',inplace=True)

In [97]:
df

,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
order_id,,,,,,,,,,
CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [98]:
df.reset_index(inplace=True)

In [99]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [100]:
df.set_index('order_id',inplace=True)
df

,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
order_id,,,,,,,,,,
CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [101]:
df.loc['CA-2020-152156']

,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
order_id,,,,,,,,,,
CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6

In [102]:
df.loc['CA-2020-152156',['order_date','sales']]

                order_date  sales
order_id
CA-2020-152156  08-11-2020  262.0
CA-2020-152156  08-11-2020  731.9

In [103]:
df.loc['CA-2020-152156','order_date':'region']

                order_date   ship_date     ship_mode customer_id region
order_id
CA-2020-152156  08-11-2020  11-11-2020  Second Class    CG-12520  South
CA-2020-152156  08-11-2020  11-11-2020  Second Class    CG-12520  South

In [104]:
df.reset_index(inplace=True)

In [105]:
df.head()

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5

#continue from 37:00